# Generated by Django 6.0.3 on 2026-03-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('file', models.FileField(help_text='The uploaded document file', upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File')], help_text='Type of document (pdf, docx, txt)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this document contains')),
                ('processed', models.BooleanField(default=False, help_text='True when document has been chunked and embedded')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if document processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content of this chunk')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True)),
                ('chunk_index', models.IntegerField(default=0, help_text='Order of this chunk in the document')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like page number, section')),
                ('char_count', models.IntegerField(default=0, help_text='Number of characters in this chunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
