# Generated by Django 6.0.3 on 2026-03-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('replies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='Platform where this conversation is happening', max_length=20)),
                ('customer_id', models.CharField(help_text='Platform-specific customer identifier', max_length=255)),
                ('customer_name', models.CharField(blank=True, help_text="Customer's name (if available)", max_length=200)),
                ('customer_email', models.EmailField(blank=True, help_text="Customer's email (if available)", max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text="Customer's phone number (if available)", max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('waiting', 'Waiting for Customer'), ('escalated', 'Escalated to Human')], default='active', help_text='Current status of the conversation', max_length=20)),
                ('needs_human_review', models.BooleanField(default=False, help_text="True if AI couldn't handle and needs human attention")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'platform', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], help_text='Whether message is from customer or business', max_length=10)),
                ('content', models.TextField(help_text='The actual message text')),
                ('response_type', models.CharField(blank=True, choices=[('predefined', 'Predefined Reply'), ('ai', 'AI Generated'), ('manual', 'Manual'), ('fallback', 'Fallback')], help_text='How the response was generated (for outbound only)', max_length=20, null=True)),
                ('ai_confidence', models.FloatField(blank=True, help_text="AI's confidence in its response (0.0 to 1.0)", null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='How long it took to generate the response (milliseconds)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('is_delivered', models.BooleanField(default=True, help_text='Whether the message was successfully delivered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
                ('predefined_reply', models.ForeignKey(blank=True, help_text='Which predefined reply was used (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='replies.predefinedreply')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], help_text='Type of messaging platform', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether auto-replies are enabled for this platform')),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='API tokens and credentials for this platform')),
                ('settings_data', models.JSONField(blank=True, default=dict, help_text='Platform-specific settings (reply delay, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connected Platform',
                'verbose_name_plural': 'Connected Platforms',
                'unique_together': {('user', 'platform_type')},
            },
        ),
    ]
