# Generated by Django 6.0.3 on 2026-03-25 13:28

import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('replies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='credentials',
        ),
        migrations.AddField(
            model_name='platform',
            name='_credentials',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, db_column='credentials', default='{}', help_text='Encrypted API tokens and credentials for this platform'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='conv_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'needs_human_review'], name='conv_user_review_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conv_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['response_type'], name='msg_response_type_idx'),
        ),
    ]
