# Generated by Django 6.0.3 on 2026-03-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_platform_credentials_platform__credentials_and_more'),
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text="Platform's unique message ID for idempotency", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp phone number ID for fast webhook lookup', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], help_text='Type of messaging platform', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id',), name='unique_external_id_when_set'),
        ),
    ]
