# Generated by Django 6.0.3 on 2026-03-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name like 'Pricing Question' or 'Location Info'", max_length=100)),
                ('keywords', models.JSONField(default=list, help_text="List of trigger words: ['price', 'cost', 'how much']")),
                ('response', models.TextField(help_text='The message that will be sent to customers')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive replies won't be used for matching")),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this reply was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predefined Reply',
                'verbose_name_plural': 'Predefined Replies',
                'ordering': ['-created_at'],
            },
        ),
    ]
